# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: "Zoé Miller"

### Header
header:
  logo:
    image: "assets/img/logo2.png"
    alt: "Zoé Miller"

### Social
social:
  - title: "Twitter"
    icon: "fab fa-twitter"
    url: "http://twitter.com"

  - title: "Dribbble"
    icon: "fab fa-dribbble"
    url: "http://dribbble.com"

  - title: "Behance"
    icon: "fab fa-behance"
    url: "http://behance.com"

### Footer
footer:
  developer: "Developed by <strong>bslthemes</strong>"
  copyright: "<strong>Luique</strong>. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "UI UX Design"
      slug: "ui-ux-design"

    - name: "Photography"
      slug: "photography"

    - name: "Development"
      slug: "development"

    - name: "Branding"
      slug: "branding"
