# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: "Zoé Miller"

### Header
header:
  logo:
    image: "assets/img/profil.png"
    alt: "Team <strong>Specialized Lille"

### Social
social:
  - title: "Facebook"
    icon: "fab fa-facebook"
    url: "https://www.facebook.com/cycleslecolier"



### Footer
footer:
  developer: "Developed by <strong>Félix</strong>"
  copyright: "<strong>Félix MOULIN</strong>. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "Route"
      slug: "route"

    - name: "Cyclo cross"
      slug: "cs"

    - name: "VTT"
      slug: "vtt"
